[env:m5stack-cores3]
platform = espressif32@6.7.0
board = m5stack-cores3
framework = arduino
build_flags =
  -D ARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  M5Unified=https://github.com/m5stack/M5Unified

; COM 番号は固定しない。
monitor_speed = 115200
upload_speed = 921600

; Browser UI embedded in the ESP32 firmware image.
board_build.embed_txtfiles =
  src/control_page.html
